version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    environment:
      DB_HOST: host.docker.internal
    ports:
      - '5000:5000'
    networks:
      - app_network

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app_network

  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_project
    ports:
      - '3307:3307'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
